export const OPEN_MODAL_ADD_ADMIN = "OPEN_MODAL_ADD_ADMIN";
export const OPEN_MODAL_EDIT_ADMIN = "OPEN_MODAL_EDIT_ADMIN";

export const CLOSE_MODAL_ADD_ADMIN = "CLOSE_MODAL_ADD_ADMIN";
export const CLOSE_MODAL_EDIT_ADMIN = "CLOSE_MODAL_EDIT_ADMIN";

export const CLIENT_REMOVE_COOKIE = "CLIENT_REMOVE_COOKIE";
export const SERVER_SET_COOKIE = "SERVER_SET_COOKIE";
export const SHOW_MODAL = "SHOW_MODAL";