// modal
export const OPEN_MODAL_ADD_ADMIN = "OPEN_MODAL_ADD_ADMIN";
export const OPEN_MODAL_EDIT_ADMIN = "OPEN_MODAL_EDIT_ADMIN";
export const OPEN_MODEL_VIEW_NEWS = "OPEN_MODEL_VIEW_NEWS";

export const CLOSE_MODAL_ADD_ADMIN = "CLOSE_MODAL_ADD_ADMIN";
export const CLOSE_MODAL_EDIT_ADMIN = "CLOSE_MODAL_EDIT_ADMIN";
export const CLOSE_MODEL_VIEW_NEWS = "CLOSE_MODEL_VIEW_NEWS";


//new
export const SET_SELECTED_NEWS = "SET_SELECTED_NEWS";
export const RESET_SELECTED_NEWS = "RESET_SELECTED_NEWS"

//admin
export const SET_SELECTED_ADMIN = "SET_SELECTED_ADMIN";
export const RESET_SELECTED_ADMIN = "RESET_SELECTED_ADMIN"

//role
export const SET_ROLES = "SET_ROLES";
export const RESET_ROLES = "RESET_ROLES"
