export const OPEN_MODAL_ADD_ADMIN = "OPEN_MODAL_ADD_ADMIN";
export const OPEN_MODAL_EDIT_ADMIN = "OPEN_MODAL_EDIT_ADMIN";
export const OPEN_MODEL_VIEW_NEWS = "OPEN_MODEL_VIEW_NEWS";

export const CLOSE_MODAL_ADD_ADMIN = "CLOSE_MODAL_ADD_ADMIN";
export const CLOSE_MODAL_EDIT_ADMIN = "CLOSE_MODAL_EDIT_ADMIN";
export const CLOSE_MODEL_VIEW_NEWS = "CLOSE_MODEL_VIEW_NEWS";

export const SET_SELECTED_NEWS = "SET_SELECTED_NEWS";
export const RESET_SELECTED_NEWS = "RESET_SELECTED_NEWS"

export const CLIENT_REMOVE_COOKIE = "CLIENT_REMOVE_COOKIE";
export const SERVER_SET_COOKIE = "SERVER_SET_COOKIE";
export const SHOW_MODAL = "SHOW_MODAL";